sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-019
env:
  global:
    -
      # LTD_AWS_ID
      secure: Avdb7g9sFOTDJtYsHcK1VPQYQ4jM6VtYrfj6zEJhz5FH/7C7exOVBbZ+aTcAdt0SwjEtJd34v8CaJhxsD0woEFtXydVuYX6Ne46kGCNKJcuYzdHiOFYp7+FIpARpbP8UpObw3RL5B0NhiYN8w2VYYga4TV+uMSJOwaK3pySeHVSc5bQeOjaoAskMOqvCMaVIyTtAxxJClhGlXQPktlxY6FtcstGB37feNtFrBm1UPEbwWXeFbvwhRiZ2LMt9LAI3vY+qYwwqpWtbJHUOIEYPbl8h2MOIL4vQSl8eIJd4FoJxfOc+rfWjW3Tjq+3cQ/lHVWfYWoG41Nd4+pWTzYm4C+PgEl7Z4ILkOnUxmkosNrSvQYL65KaHSzscPYV+4eExcQY/B+ZXW+bypFq/KAfjxbQ0zdClvTWUod6WdJY/8ovo59nydnRF7auB+wmSttsIcw6bj7oBFJ9fl1ETfyR2J4gPsHLBJSNyyKjkzghfakndPkAufTDjNURul9VtdmCnpL4Xcfch4mThHuB5lthE+8dnth29aChbxHjHDdkeZSRj+8AShyO1K23wLqFoVhWRZ/gztmh/g93kg+UomFqoMuviWAlcAVVGJLiP0LqFYB0MtICKQPlnYX+6ASMMmi3cPrNdM47oSIc3/B/oP51ku1djDixcZt9abp9cux+Qrvg=
    -
      # LTD_AWS_SECRET
      secure: ic6uxTFUtmC/By+7PE7H0pRLjN8vGE1qhFI60od1+mtiDhpenjTuX62rNyR/oPND8Hc4lSZESsRCeD5wEFzb++HqGMY97D16/phR5IEyHh7hC3mwsT+zmBHzXKVaRmiNcl39tf8hy0EpBMVFTd0aXUrSxFd2xP0Ak2J7r/9aKaJXvzYoryJIdRBRQyxLeMsB57qKPowPXO0vB7AkTDCVOY5DPTTPxscMsoM4Tsq9Zp2pp9ogvMyg8sE57Zn3MGjjUWAanMLInOGPlqGkGlwVZAZySPD/L5ccKkh9OQwE+9SgwwRS+dBHMA/+SNQXum3dTkTTLcHTtMPr8lMDyF0GiJIAauxs06ctRVgKzfoW/3L/9FUG+k7yXfGER0fcHCUUkh8RNK8Z8H7TyuqZCwxlMhnJAChJP1Pio59m/YbaStkjpNtzK52AQC/Rxq8fAgGd79zE2Er6jC8QXe7Xh9O482ojZmUeNOiv+Dw9hWhwivz/nUe/zdwQAXo2qXRpcfzFif+7d5fx+Iwoo9WOSRgZVS9ew7LdvF89dyzAYPLaXfnSj2ajNfWz8s9l0R6SVyHnrRQNeZ+oU3ex9he1csOfXDLQ4R0p/yewGy429WZkJHMniAXpY+bS8u2YmEj+oqvU9okTtZ4lSUh3oaMdQrEVM+Vu3U1/ZmMojGpp4l1YGPs=
    -
      # LTD_USERNAME
      secure: AWLbvKwQzmadW1nqBp23AlE6f9wjtdrTm/HyLxGLHWVlbfkdaoyBEQsFTyGxRcqjnKAtvlg191J5JAJeYX9O/n//W91k+dGg1chckktvLaNs4RCnAYoOQKcxBvjo8J0v9BqHd9R3m+F+Ql9uhDPENnM482JzpK5QFGj7gdlunsOAaTlxCjP7JWxepuXlWRxcfShYEL1UZ2WHOHDaPmxtyBfUvF5Zt8f0puF4KEyGXi+CtMuouBMeAA2ZTHIltBiP5Plzxyo6biSSEDRid5rVCDYNC7xBW0k99Fbmi26/rKNEOBFDOUOJ2IlTbhpgtPNS1x55Ao93dj16wlA2OQaKnI728DsbU/FZpjxNrlVqN9wvehxHoIT4wY7YjMAsfmybJ3svqLtEkq/mnYajBZt+ij+0dN+zO4niQxA1RRywLc7OITlQJItlQqe77YQkdnIwieLreyGX9hg0zXIfQzdNSlhgp7k8fe+BrR/flc3uamVL/mVN75qh9WuBPU52NBOUsAlYT1utDMgzjGMe2shHPNv+BpHDnqMX/mIVwHv8T/tpf1rOg3Z3Msiov/G8LUINVhuKadWm8OO9dn89oITbqVOFaLuWiD/ObtC+AjF5dnwyuJiqZWsJUgAK+WWGc0m5bSalsIPWHqg/iNCpjz12QkZ+mwrH2U9pELTiMXV7jk0=
    -
      # LTD_PASSWORD
      secure: dH2wK0w/uZiZJ8aSS0ZAJA2//H+5VVa0+3SURDuceNlr/VEwEK+wZVJpLqNtu3PAX1zO7SF/uiFiCCe3XtuagzVWoQqrSzeWJ69+r4xLzkxWWH3UCRwL0pyvkM1HRICKThWbwa+8XtZD9OgCKZYI1ii+vvKXuNYtoWAZ06TqexHl42Rw2GJtcn3M7jnPz9nUBsN/RGZ5u9cqpDbjkPzjOtDDwFXnUB+a8vVBgPvnEkqLI2jO+rzPQApGT6KI5dU8b7vzJ2l3Ag7oDnmwm5VzMx+X/MIhZRfzhWoV+ZzUnSswIw7k0ML7ACgS1IEvM+VaNRzINYOZNP+goviyKiQhTSMliheq37JlcucRLvhLe+nallDueGmv6zOjZIsc59yJZOZDAKijNSAWyMNNCKpY2R8iCUS4BJcvYWqWhtOXdVa2mbhmpFsnOoZSHBO5JnGt5Q1oj2dUd2vX1EZPKYr3hL47p0JZa7ZTSbXeoafFYnTfywSZtR6ueNw/+PskYryST8BuCynab+gptLKUllMTAgY5eMzNsODkWyNEWspOEW+0RKejlIKCTsLJRwVorUO/CXffJ8uwPG6vC3FMTKX3RNEVQvytX6eV71WBMN9FF2Dx8/rcg+sRwk7DFcuZ/45xjRs+byLUfxzdBT5JsDn1GWPrDtnBqEyNWCLRQ+lvD00=
